### ISSUE TITLE
Data sources

### ISSUE THREAD

**Issue by motapinto** [rheinzler/PointCloudDeNoising#21]
In [DENSE datasets page](https://www.uni-ulm.de/en/in/driveu/projects/dense-datasets) it mentions the following:
> "For the challenging task of lidar point cloud de-noising, we rely on the [Pixel Accurate Depth Benchmark](https://www.uni-ulm.de/en/in/driveu/projects/dense-datasets#c811604) and the [Seeing Through Fog](https://www.uni-ulm.de/en/in/driveu/projects/dense-datasets#c811875)(STF) dataset recorded under adverse weather conditions like heavy rain or dense fog. In particular, we use the point clouds from a Velodyne VLP32c lidar sensor."

Could you further explain please?

In particular, my questions are the following:
1. Is the data exclusively from those 2 sources (mentioned in the Dense webpage), except the train_road_01 and train_road_02 folders which contain the road data you collected and is not labeled, or does it add some data? This is unclear, especially since the dataset from this repository contain 6.6k clear weather frames (train, test, val folders) but the STF(Seeing Through Fog) dataset mentions using only 5.5k clear weather frames, for the real world recording, which is not used. The climate chamber data it uses contains only 364 clear weather frames according to [this paper](https://ieeexplore.ieee.org/abstract/document/9575320/) (TABLE I). So, does this mean that the other 6.3k clear weather frames data comes from the **Pixel-Accurate Depth Evaluation in Realistic Driving Scenarios** dataset?
4. What part of the data is being used from those papers. From #13 you suggest to use the STF road data data, but in the [DENSE datasets page](https://www.uni-ulm.de/en/in/driveu/projects/dense-datasets) it mentions that the [Seeing Through Fog](https://www.uni-ulm.de/en/in/driveu/projects/dense-datasets#c811875) dataset is being used, so I presume that only the climate chamber data of the STF dataset is included. 
13. Is the data from the climate chamber in STF and ** "Pixel-Accurate Depth Evaluation in Realistic Driving Scenarios" ***different from each other, the exact same data, or does it contain some overlap?
14. Of the data used from both papers/datasets, is there any change to the data from both papers, or does it contain exactly the same data, in terms of quantity, diversity, distribution?

Essentially, I am confused with the different datasets available in DENSE webpage, and to avoid repetition I am trying to understand overlaps in the data being used. The Dense webpage contains the following datasets to download:
- cnn_denoising (the one refering to this github repo)
- FogChamberDataset
- SeingThroughFog
- pixel_accurate_depth_benchmark

Since all these datasets are referred or mention in the paper, Dense webpage, github issues could you explain me, or point to where should I look, to solve this confusion?

Sorry for the long question xD

**Comment by rheinzler** [comment]
1. Yes there is no point-wise label for road data. All static scenes are identical with the data from “ Pixel-Accurate Depth Evaluation in Realistic Driving Scenarios”.
2. No the issue only refers to road data. 
3. I cannot answer this question as I am not the author of all of theses papers. 

So basically the data used for each paper is stated at the dense website. There is some overlap, especially for the static scenes, as you can see in the data itself. So for the static scenes you can say the data is identical with this paper (Pixel-Accurate Depth Evaluation in Realistic Driving Scenarios). Basically the scenarios were selected for the Pixel-Accurate paper and also used for the de-noising paper. But there is some difference in preprocessing the data, for example the data is cropped to a 32x400 forward facing view (de-noising). 

For the STF paper we used a similar road dataset. There might be some difference in the absolut number of frames for different scenes. In the de-noising paper we do not use any object labels and can therefore use the data as it is. The STF data contains manually annotated ground truth object labels and might therefore be preselected. Due to paper deadlines and the manual annotation process, we were not able to perfectly synchronize these road datasets. 

I hope this helped. Otherwise please reopen the issue.
