### ISSUE TITLE
Dataset comparison and output for PixelAccurateDepthEstimation

### ISSUE THREAD

**Issue by anupamsobti** [rheinzler/PointCloudDeNoising#7]
Hi 

I'm wondering if you've released the denoised output for the chamber data used in the paper Pixel-Accurate Depth Evaluation in Realistic Driving Scenarios (https://ieeexplore.ieee.org/abstract/document/8885465/). The images in this paper look similar to the other paper. Please let me know if there is correspondence and which split I should refer to.

Thanks!

**Comment by rheinzler** [comment]
Hi @anupamsobti. The repo is referred to this ICRA [paper](https://ieeexplore.ieee.org/document/8990038). However, the data for both paper were recorded within the same project. That's why the data look quite similar. You can find an overview about other papers from this project [here](https://www.uni-ulm.de/in/iui-drive-u/projekte/dense-datasets/). I hope this helps.

**Comment by anupamsobti** [comment]
Thanks for your reply. I understand these are different papers and repositories. However, if the corresponding denoised output is released, it might still help further research. Since the group has not released trained models or code, I was wondering if the denoised output corresponds to the dataset mentioned in the depth benchmark. 
As I understand, until today, we do not have this corresponding data available.

**Comment by rheinzler** [comment]
Yes, that is correct, the data is not yet available. Due to legal regulations, an additional release is very costly and complicated, as the data was recorded in cooperation with several companies. I do not believe that we can make this data available without further consideration. Sorry, for this unfortunately unsatisfactory answer.
